<a href="https://colab.research.google.com/github/FahimShahriarAnik/NLP/blob/main/numpuy_activity.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
# create a numpy array of size 7*5 initializing with random values between -5 to 5

#count the number of items less than -1

# next, add 5 to each of the item with value less than 0

# now, reshape the array to 5*7 and use broadcasting to add another array [1,2,3,4,5]

# finally, print the first value for axis 0

(4,)


In [ ]:
import numpy as np

# Step 1: Create a numpy array of size 7x5 with random values between -5 and 5
array = np.random.uniform(-5, 5, (7, 5))

print(f"array: {array}\n")

# Step 2: Count the number of items less than -1
count_less_than_negative_one = np.sum(array < -1)
print(f"count_less_than_negative_one: {count_less_than_negative_one}\n")

# Step 3: Add 5 to each of the items with value less than 0
array[array < 0] += 5
print(f"new array: {array}\n")
# Step 4: Reshape the array to 5x7
reshaped_array = np.reshape(array, (5, 7))
print(f"reshaped_array: {reshaped_array}\n")

# Step 5: Add the array [1,2,3,4,5] to the reshaped array using broadcasting
broadcast_array = np.array([1, 2, 3, 4, 5]).reshape(5, 1)
print(f"broadcast_array: {broadcast_array}\n")
final_array = reshaped_array + broadcast_array
print(f"final_array: {final_array}\n")
# Step 6: Print the first value for axis 0
first_value_axis_0 = final_array[0, 0]
print(f"first_value_axis_0: {first_value_axis_0}\n")


array: [[ 4.40657782 -0.3851513   2.26057693 -0.35955007  2.81818017]
 [ 0.82596709  1.23187637  4.28356108 -0.60467145 -3.3528394 ]
 [-4.2457405   1.11749654 -2.12781046  2.91102939  0.58632526]
 [ 3.80754364 -0.8318474  -0.27613485  2.94332156  3.23178546]
 [ 1.96380398 -4.17949483 -0.48266438  3.73933666  0.23380721]
 [-1.34289558  2.16414299 -2.65098907  1.87002666 -0.80190939]
 [ 4.93668205  4.08391875  2.49215683  4.99830144 -1.764183  ]]

count_less_than_negative_one: 7

new array: [[4.40657782 4.6148487  2.26057693 4.64044993 2.81818017]
 [0.82596709 1.23187637 4.28356108 4.39532855 1.6471606 ]
 [0.7542595  1.11749654 2.87218954 2.91102939 0.58632526]
 [3.80754364 4.1681526  4.72386515 2.94332156 3.23178546]
 [1.96380398 0.82050517 4.51733562 3.73933666 0.23380721]
 [3.65710442 2.16414299 2.34901093 1.87002666 4.19809061]
 [4.93668205 4.08391875 2.49215683 4.99830144 3.235817  ]]

reshaped_array: [[4.40657782 4.6148487  2.26057693 4.64044993 2.81818017 0.82596709
  1.23187637]
